#include "stm32f1xx_hal.h"
#include "tim.h"

// Fan speed PWM config
#define ECU_COOLING_FAN_TIMMER_CHANNEL TIM_CHANNEL_1
#define ECU_COOLING_FAN_LOW_SPEED 300
#define ECU_COOLING_FAN_MEDIUM_SPEED 600
#define ECU_COOLING_FAN_HIGH_SPEED 1000

#define ECU_COOLING_TEMPERATURE_RANGE_LOW 50
#define ECU_COOLING_TEMPERATURE_RANGE_MEDIUM 70
#define ECU_COOLING_TEMPERATURE_RANGE_HIGH 90

#define ECU_COOLING_TEMPERATURE_KF_ERROR_MEASUREMENT 2
#define ECU_COOLING_TEMPERATURE_KF_ERROR_ESTIMATE 2
#define ECU_COOLING_TEMPERATURE_KF_PROCESS_NOISE 0.01


void ECU_Cooling_Init();
void ECU_Cooling_Check();
void ECU_Cooling_Set_Fan_Speed(int8_t speed);
float ECU_Cooling_Read_Temp();