#ifndef CBCR_LIGHT_H
#define CBCR_LIGHT_H

#define CBCR_LIGHT_DAYTIME (uint16_t)0x1                 // Front daytime
#define CBCR_LIGHT_BEAM_LOW (uint16_t)0x2                // Front low beam
#define CBCR_LIGHT_BEAM_HIGH (uint16_t)0x4               // Front high beam
#define CBCR_LIGHT_INDICATOR_FRONT_LEFT (uint16_t)0x8    // Front left indicator
#define CBCR_LIGHT_INDICATOR_FRONT_RIGHT (uint16_t)0x10  // Front right indicator
#define CBCR_LIGHT_INDICATOR_REAR_LEFT (uint16_t)0x20    // Rear left indicator
#define CBCR_LIGHT_INDICATOR_REAR_RIGHT ((uint16_t)0x40) // Rear right indicator
#define CBCR_LIGHT_REAR_POSITION ((uint16_t)0x80)        // Rear position
#define CBCR_LIGHT_REAR_BRAKE ((uint16_t)0x100)          // Rear brake
#define CBCR_LIGHT_REAR_TAG_LICENSE ((uint16_t)0x200)    // Rear tag

#define CBCR_LIGHT_INDICATORS_FRONT CBCR_LIGHT_INDICATOR_FRONT_LEFT | CBCR_LIGHT_INDICATOR_FRONT_RIGHT
#define CBCR_LIGHT_INDICATORS_REAR CBCR_LIGHT_INDICATOR_REAR_LEFT | CBCR_LIGHT_INDICATOR_REAR_RIGHT
#define CBCR_LIGHT_INDICATORS_LEFT CBCR_LIGHT_INDICATOR_FRONT_LEFT | CBCR_LIGHT_INDICATOR_REAR_LEFT
#define CBCR_LIGHT_INDICATORS_RIGHT CBCR_LIGHT_INDICATOR_FRONT_RIGHT | CBCR_LIGHT_INDICATOR_REAR_RIGHT
#define CBCR_LIGHT_INDICATORS_ALL CBCR_LIGHT_INDICATORS_FRONT | CBCR_LIGHT_INDICATORS_REAR;

#endif