#!/usr/bin/env bash

HOST_OS=$(uname -s | awk '{print tolower($0)}')

DIR_SCRIPTS="$(dirname ${BASH_SOURCE[0]})"
DIR_SYSROOT="$DIR_SCRIPTS/../sysroot"
DIR_TOOLCHAIN="$DIR_SCRIPTS/../toolchain/$HOST_OS"
DIR_PATCHES="$DIR_SCRIPTS/../patches"

source "$DIR_SCRIPTS/env"