#!/usr/bin/env bash

SCRIPT_SHELL_NAME="$0"
SCRIPT_SHELL_ARGS="$@"
SCRIPT_SHELL_FILENAME=$(basename $0)
SCRIPT_DIR=$(cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd)

source "$SCRIPT_DIR/pkg"
source "$SCRIPT_DIR/env"

DIR_PWD=$(pwd)
DIR_TMP="$(mktempd $SCRIPT_SHELL_FILENAME)"
LOGFILE="$(pwd)/$SCRIPT_SHELL_FILENAME.log"
DEVTOOL_KINDS="req stm rpi"

while [[ $# -gt 0 ]]; do
  case $1 in
    --clean)
      rm -rf $DIR_TMP
      exit $?
    ;;
    *)
      shift 1
    ;;
  esac
done 

log_init $LOGFILE $SCRIPT_SHELL_ARGS

if is_flag_present '--verbose' $SCRIPT_SHELL_ARGS; then
  printenv
fi

if ! $DIR_SCRIPTS/install-requirements \
  --logfile $LOGFILE $SCRIPT_SHELL_ARGS $DIR_BASE/requirements.txt; then
  log_errexit "Error installing requirements"
fi

for kind in $DEVTOOL_KINDS; do
  pkg_config_parse \
    $DIR_BASE/pkg-${kind}-devtools.conf \
    --toolchaindir $DIR_TOOLCHAIN \
    --tempdir $DIR_TMP \
    --logfile $LOGFILE \
    $SCRIPT_SHELL_ARGS
done